logging:
  level:
    com.microsoft.eventhub: INFO
    root: INFO
  pattern:
    console: "[%d{HH:mm:ss}] %-5level %logger{36} - %msg%n"

eventhub:
  region: ${REGION:uksouth}
  subscription-id: ${SUBSCRIPTION_ID:ef5bdf4d-e9c1-4ea3-a8c3-fa5b35bcf7c3}
  resource-group: ${RESOURCE_GROUP:eh-lag-metric-rg}
  tenant-id: ${TENANT_ID:16b3c013-d300-468d-ac64-7eda0820b6d3}
  event-hub-namespace: ${EVENT_HUB_NAMESPACE:eh-lag-metric}
  event-hub-name: ${EVENT_HUB_NAME:eh-lag-metric-eh}
  consumer-group: ${CONSUMER_GROUP:$Default}
  checkpoint-account-name: ${CHECKPOINT_ACCOUNT_NAME:ehlagmetricsa}
  checkpoint-container-name: ${CHECKPOINT_CONTAINER_NAME:eh-lag-metric-container}
  custom-metric-interval: ${CUSTOM_METRIC_INTERVAL:10000}
  managed-identity-client-id: ${MANAGED_IDENTITY_CLIENT_ID:e0a7009c-b39d-4245-b5f8-c1dd487f46e8}

# Application Insights
azure:
  application-insights:
    connection-string: ${APPLICATIONINSIGHTS_CONNECTION_STRING:InstrumentationKey=b5965a4f-ece5-44da-a1db-edb49acec627;IngestionEndpoint=https://uksouth-1.in.applicationinsights.azure.com/;LiveEndpoint=https://uksouth.livediagnostics.monitor.azure.com/;ApplicationId=6f9453e2-b2bf-4a32-85b4-9ff5d6014b1f}